Added Book entity, BookRepository and BookService
Serhii-Nosulia/book-shop-app pull request #1
Opened 2023-11-10 16:29 UTC by Serhii-Nosulia

2023-11-10 17:10 UTC, Ivan95kos requested changes
Good job overall!

2023-11-10 17:10 UTC, Ivan95kos commented on src/main/java/mate/bookshopapp/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
You should not use `JpaRepository` in this part

`BookRepository` interface with methods and `BookRepositoryImpl` class:
```
Book save(Book book);
List findAll();
```

2023-11-10 17:10 UTC, Ivan95kos commented on src/main/java/mate/bookshopapp/service/impl/BookServiceImpl.java
> +    @Autowired
Here You don't need to use `@Autowired`, you can remove it

2023-11-10 18:08 UTC, Serhii-Nosulia commented on src/main/java/mate/bookshopapp/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
When I add SessionFactory to BookRepository, I have this problem, and I don't know how fix it
<img width="867" alt="Знімок екрана 2023-11-10 о 20 04 43" src="https://github.com/Serhii-Nosulia/book-shop-app/assets/122731374/781c5b90-c264-4040-8cd5-29acf632d972">

2023-11-11 17:34 UTC, Ivan95kos approved these changes
Nice

2023-11-16 15:12 UTC, merged