Add CartItem, ShoppingCart entity and missing features
Serhii-Nosulia/book-shop-app pull request #12
Opened 2024-01-20 11:51 UTC by Serhii-Nosulia

2024-01-20 17:27 UTC, olekskov requested changes

2024-01-20 17:27 UTC, olekskov commented on src/main/java/mate/bookshopapp/service/impl/ShoppingCartServiceImpl.java
> +        }
For me it's more logical to increase quantity of book in cart rather then throw exception

2024-01-20 17:27 UTC, olekskov commented on src/main/java/mate/bookshopapp/service/impl/ShoppingCartServiceImpl.java
> +        return cartItemMapper.toSetQuantityDto(cartItemsRepository.save(cartItem));
Better to introduce check that updated cart item is in cart of user that is logged in. Now you may easily change quantity of cart item in other user cart

2024-01-20 17:27 UTC, olekskov commented on src/main/java/mate/bookshopapp/service/impl/ShoppingCartServiceImpl.java
> +        cartItemsRepository.deleteById(id);
same here

2024-01-20 17:27 UTC, olekskov commented on src/main/java/mate/bookshopapp/repository/shopping/cart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findShoppingCartById(@Param("id") Long id);
Should work without query
```
    @EntityGraph(attributePaths = {"cartItems", "cartItems.book"})
    Optional<ShoppingCart> findById(Long id);
```

2024-01-21 11:14 UTC, Ivan95kos approved these changes
Great job

2024-01-21 17:47 UTC, merged