added CustomGlobalExceptionHandler
Serhii-Nosulia/book-shop-app pull request #6
Opened 2023-11-29 21:38 UTC by Serhii-Nosulia

2023-11-30 12:35 UTC, Sanderfuck requested changes

2023-11-30 12:35 UTC, Sanderfuck commented on src/main/java/mate/bookshopapp/exception/CustomGlobalExceptionHandler.java
> +        body.put("errors", errors);
You can use constants for strings

2023-11-30 12:35 UTC, Sanderfuck commented on src/main/java/mate/bookshopapp/dto/book/UpdateBookDto.java
>                              String coverImage) {
Only one field validated?

2023-11-30 12:35 UTC, Sanderfuck commented on src/main/java/mate/bookshopapp/dto/book/CreateBookRequestDto.java
>                                     String description,
Validate description by max size, find validate case for ibn

2023-12-01 11:49 UTC, okuzan requested changes

2023-12-01 11:49 UTC, okuzan commented on src/main/java/mate/bookshopapp/dto/book/UpdateBookDto.java
> +                            @NotNull String author,
for strings let's use NotBlank
https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2023-12-01 13:09 UTC, okuzan approved these changes

2023-12-02 16:12 UTC, merged